// Days of the week

#table(
type table
    [
        #"DayNum"=number,
        #"DayName"=text,
        #"DayAbbr"=text,
        #"DayAbbrLetter"=text
    ],
 {
  { 1 ,	"Sunday"	, "Sun"	, "U"	},
  { 2 ,	"Monday"	, "Mon"	, "M"	},
  { 3 ,	"Tuesday"	, "Tue"	, "T"	},
  { 4 ,	"Wednesday"	, "Wed"	, "W"	},
  { 5 ,	"Thursday"	, "Thu"	, "R"	},
  { 6 ,	"Friday"	, "Fri"	, "F"	},
  { 7 ,	"Saturday"	, "Sat"	, "S"	}
 }
)